#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland

# export RUST_BACKTRACE=full


# Get current window state.
: "$(hyprctl activewindow -j | jaq '.mapped')"

case $1 in
  dock)
    # open the dock onhover if current window is free.
    [[ $_ != "true" ]] && eww update dock-visible=true
esac

