#!/usr/bin/env bash
# Hyprwwland > by darkmaster grm34.
# export RUST_BACKTRACE=full

# Get date and time.
readarray -td/ date < <(date '+%d/%m/%Y/%H:%M/')

# Return as JSON.
printf '{
  "date": "%s",
  "time": "%s",
  "day": "%s",
  "month": "%s",
  "year": "%s"
}' "${date[0]}/${date[1]}/${date[2]}" "${date[3]}"\
   "${date[0]}" "${date[1]}" "${date[2]}"

