#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland

# export RUST_BACKTRACE=full


# Get date and time.
readarray -td/ date < <(date '+%d/%m/%Y/%H:%M/')

# Return as json.
printf '{
  "date": "%s",
  "time": "%s",
  "day": "%s",
  "month": "%s",
  "year": "%s"
}' "${date[0]}/${date[1]}/${date[2]}" "${date[3]}"\
   "${date[0]}" "${date[1]}" "${date[2]}"

