#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland


# Get required settings from config.json.
readarray -t config < <(
  jaq '.dock_app_path,
       .dock_app_icon_path,
       .dock_app_icon_size,
       .terminal_cmd' "$PWD/config.json")
app_path="${config[0]//\"}"
icon_path="${config[1]//\"}"
icon_size="${config[2]//\"}"
terminal_cmd="${config[3]//\"}"


# Get user applications.
readarray -t apps < <(
  fd . "$app_path" --min-depth 0 --max-depth 2 \
                   --type file --extension desktop)


# Create an array containing the required data of each app.
index=0
app_data=()
for app in "${apps[@]}"; do
  ((index > 14)) && break # max 15 apps.

  # skip "nodisplay"/"Qt"/"icon less" apps.
  grep -qm 1 "NoDisplay=true\|Categories=Qt" "$app" && continue
  : "$(grep -m 1 "^Icon=" "$app")"
  : "$icon_path/${_//Icon=}.svg"
  ! [[ -f $_ ]] && continue

  # get app name.
  : "$(grep -m 1 ^Name= "$app")"
  name="${_//Name=}"

  # get app icon.
  : "$(grep -m 1 "^Icon=" "$app")"
  icon="$icon_path/${_//Icon=}.svg"

  # get opening cmd.
  : "$(grep -m 1 ^Exec "$app")"
  : "${_//Exec=}"
  : "${_//\"}"
  : "${_%% *}"
  cmd="$(which "$_") &"
  [[ $cmd == *"mpv &"* ]] && # fix mpv exec.
    cmd="${cmd//mpv/mpv --player-operation-mode=pseudo-gui}"

  # define opening cmd (terminal or standalone).
  grep -qm 1 "Terminal=true" "$app" && cmd="$terminal_cmd $cmd"
  [[ ${cmd// &} == *alacritty ]] && # open $TERM from $HOME (fix).
    cmd="${cmd// &} --working-directory $HOME &"

  # increment the array.
  printf -v data \
    '{"name": "%s", "icon": "%s", "size": "%s", "cmd": "%s"},' \
    "$name" "$icon" "$icon_size" "$cmd"
  app_data+=("$data")

  # increment the index.
  index=$((index + 1))
done


# Return as json.
: "${app_data[*]}"
printf '%s' "[${_::-1}]" # Hmm, anything else?

