#!/usr/bin/env bash
# Hyprwwland > by darkmaster grm34.
# export RUST_BACKTRACE=full

# This script is not used at the moment.
: "$(hyprctl devices -j\
  | jq '.keyboards?[0].active_keymap')"
: "${_//\"}" && : "${_:0:2}"
printf '%s' "${_^^}"

