#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland

# This script is executed by a polling variable.
# It recursively scans a folder for applications and
# returns a yuck widget containing each shortcut found.

# export RUST_BACKTRACE=full


# Get required settings from config.json.
readarray -t config <\
  <(jaq '.launcher_app_path,
         .launcher_app_icon_path,
         .terminal_cmd' "$PWD/config.json")

# Remove double quotes.
app_path="${config[0]//\"}"
icon_path="${config[1]//\"}"
terminal_cmd="${config[2]//\"}"

# Get user apps.
readarray -t apps\
  < <(fd . "$app_path"\
           --min-depth 0 --max-depth 2\
           --type file --extension desktop)

# Create a widget for each app.
box=
for app in "${apps[@]}"; do

  # skip nodisplay apps.
  grep -qm 1 "NoDisplay=true" "$app" && continue

  # check for app icon (use help icon if none found).
  : "$(grep -m 1 "^Icon=" "$app")"
  icon="$icon_path/${_//Icon=}.svg"
  ! [[ -f $icon ]] && icon="$icon_path/help_index.svg"

  # get app real name.
  : "$(grep -m 1 ^Name= "$app")" && name="${_//Name=}"

  # get app executable.
  : "$(grep -m 1 ^Exec "$app")"
  : "${_//Exec=}" && : "${_//\"}" && : "${_%% *}"

  # define the opening cmd (terminal or standalone). 
  cmd="$(which "$_") &"
  [[ $cmd == *"mpv &"* ]] && # fix mpv exec.
    cmd="${cmd//mpv/mpv --player-operation-mode=pseudo-gui}"
  { grep -qm 1 "Terminal=true" "$app"\
    || [[ $cmd == *himalaya* ]] ;} && # fix himalaya exec.
      cmd="$terminal_cmd ${cmd//himalaya/himalaya write}"
  [[ ${cmd// &} == *alacritty ]] && # open terminal from HOME.
    cmd="${cmd// &} --working-directory $HOME &"  
  cmd="eww close launcher_popup; $cmd"

  # create the widget.
  box="$box
  (eventbox :class \"launcher-popup-app\" :tooltip \"$name\"
            :onclick \"$cmd\" :cursor \"pointer\"
    (box :orientation \"v\" :space-evenly false
         :class \"launcher-popup-app-icon\"
      (image :path \"$icon\" :image-width 38)
      (label :text \"$name\" :limit-width 12)))"
done

printf '%s' "(box $box)" # This should output something...

