#!/usr/bin/env bash

# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland

# This script is executed by a polling variable
# but can also be executed by user events (button).
# It simply controls the management of the sleep mode.

# export RUST_BACKTRACE=full

# Get required settings from config.json.
readarray -t config <\
  <(jaq '.suspend_timeout,
         .sleep_timeout,
         .lock_effects,
         .standby_wallpaper' "$PWD/config.json")

# Run swayidle and hyprctl.
function standby_mode() {
  pkill -f -9 swayidle
	: "swaylock -F -e ${config[2]//\"} -i ${config[3]//\"}"
	swayidle timeout "${config[0]//\"}" "$_"\
	         timeout "${config[1]//\"}" "hyprctl dispatch dpms off"\
	         resume "hyprctl dispatch dpms on" &
}

case $1 in
  on)
    # onclick: activate.
    eww update standby=true
    standby_mode
    ;;
	off)
    # onclick: deactivate.
    eww update standby=false
    pkill -f -9 swayidle
    ;;
  *)
    # onpoll: activate if required and return state (bool).
    : "$(eww get standby)"
    [[ $_ == "true" ]] && standby_mode
    if [[ $_ ]]; then
      printf '%s' "$_"
    else
      printf '%s' "true"
    fi
esac

