#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland


# Get required settings from config.json.
readarray -t config <\
  <(jaq '.suspend_timeout,
         .sleep_timeout,
         .lock_effects,
         .standby_wallpaper' "$PWD/config.json")

# Run swayidle with hyprctl.
function activate_standby_mode() {
  if ! pidof swayidle &>/dev/null; then
	  : "swaylock -F -e ${config[2]//\"} -i ${config[3]//\"}"
	  swayidle timeout "${config[0]//\"}" "$_"\
	           timeout "${config[1]//\"}" "hyprctl dispatch dpms off"\
	           resume "hyprctl dispatch dpms on" &
  fi
}

case $1 in
  on)
    # onclick: activate.
    eww update standby=true
    activate_standby_mode
    ;;
	off)
    # onclick: deactivate.
    eww update standby=false
    pkill -f -9 swayidle
    ;;
  *)
    # onpoll: activate if required.
    : "$(eww get standby)"
    [[ $_ == "true" ]] && activate_standby_mode
esac

