#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland


case $1 in
  updates)
    : "2"
    printf '%s' "$_"
    ;;
  standby)
    : "false"
    printf '%s' "$_"
    ;;
  brightness)
    : "$(light -G | cut -d'.' -f1)"
    printf '%s' "$_"
    ;;
  volume)
    : "$(pulsemixer --get-volume | cut -d' ' -f1)"
    printf '%s' "$_"
    ;;
  network)
    : "$(nmcli networking connectivity)"
    printf '%s' "$_"
    ;;
  datetime)
    readarray -td/ date < <(date '+%d/%m/%Y/%H:%M/')
    printf '{"date":"%s","time":"%s","day":"%s","month":"%s","year":"%s"}' \
      "${date[0]}/${date[1]}/${date[2]}" "${date[3]}" \
      "${date[0]}" "${date[1]}" "${date[2]}"
esac

