#!/usr/bin/env bash
# Hyprwwland Copyright (c) 2023 darkmaster grm34.
# https://github.com/grm34/Hyprwwland


# Get current window state.
: "$(hyprctl activewindow -j | jaq '.mapped')"


# Handle requests.
case $1 in
  dock)
    # open the dock onhover if the current window is free.
    [[ $_ != "true" ]] && eww update dock_visible=true
    ;;
esac

